/***************************************************************
*  DO NOT EDIT THIS FILE!
*         
*  This file is automatically generated by HP Service Test.
*  Manually changing the contents of this file may result in 
*  loss of information.
*          
*  To edit the test, open the file ?{testName}.st? 
*  in HP Service Test.
 ***************************************************************/
namespace Script
{
    using System;
    using HP.ST.Fwk.SOAReplayAPI;

    public partial class WorkFlowScript
    {
        private string GetPipeName()
        {
            if (VuserClass.CommandLineArguments != null)
            {
                for (int i = 0; i < VuserClass.CommandLineArguments.Length; i++)
                {
                    if (VuserClass.CommandLineArguments[i].Equals("-st_replayapi_pipename", StringComparison.OrdinalIgnoreCase))
                    {
                        return VuserClass.CommandLineArguments[i + 1];
                    }
                }
            }
            return String.Empty;
        }

        private void LoadTestInput()
        {
            try
            {
                string pipeName = this.GetPipeName();
                if (!String.IsNullOrEmpty(pipeName))
                {
                    ReplayServiceClient replayServiceClient = new ReplayServiceClient();
                    replayServiceClient.Connect(pipeName);
                    _context.ReplayClient = replayServiceClient;
                }
                else
                {
                    this._context.ReplayClient = new FileSystemReplayClient(this._context.ScriptPath);
                }

                TestInput input = _context.ReplayClient.OnTestExecuting();
                _context.TestProfile = input.EnvironmentProfiles.ActiveProfile;
                _context.TestInputParameters = input.TestInputParameters;
                _context.TestOutputParameters = input.TestOutputParameters;
                _context.ReportDirectory = input.ReportDirectory;
                _context.ResourceManager = input.RuntimeResourceManager;
                _context.ReportMode = input.ReportMode;
                input.EnvironmentProfiles.TestSystemVariables = new HP.ST.Ext.BasicActivities.RuntimeTestVariables(this._context);
                input.EnvironmentProfiles.QcSystemVariables = new HP.ST.Ext.BasicActivities.RuntimeQcVariables(this._context);
            }
            catch (Exception ex)
            {
                _context.UserLogger.Error("Couldn't Load Test Input", ex);
                
            }
        }
    }
}